---

- name: Template Cantaloupe Properties
  template:
    src: cantaloupe.properties.j2
    dest:  "{{ cantaloupe_properties_path }}/cantaloupe.properties"
    owner: "{{ cantaloupe_user }}"
    group: "{{ cantaloupe_group }}"
