---
- name: install dependencies with yum
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - unzip
    - wget

- name: create cantaloupe user
  user:
    name: cantaloupe
    shell: /bin/bash
    state: present

- include: install.yml

- include: config.yml

- include: service.yml

- name: Ensure cantaloupe service is started
  service:
    name: cantaloupe
    state: started
