---

- name: install dependencies with yum
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - unzip
    - wget

- include: install.yml
  tags:
    - cantaloupe
    - cantaloupe-install

- include: web.yml
  tags:
    - cantaloupe
    - cantaloupe-web
  when: cantaloupe_deploy_war

- include: config.yml
  tags:
    - cantaloupe
    - cantaloupe-config

- include: cache.yml
  tags:
    - cantaloupe
    - cantaloupe-cache
  when: cantaloupe_create_FilesystemCache_dir
