---
- include: prereqs.yml

- include: install.yml

- include: config_general.yml

- include: config_sources.yml

- include: config_processors.yml

- include: service.yml

- name: Ensure cantaloupe service is started
  service:
    name: cantaloupe
    state: started
