---
- name: Create systemd unit file
  template:
    src: cantaloupe.service.j2
    dest: "{{ cantaloupe_systemd_path }}/cantaloupe.service"

- name: Reload systemd daemon
  command: "systemctl daemon-reload"
